In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import layers, Model

In [2]:
# my notes

# follow up on climatology precipitation & temperature
# challenges
# entity embeddings
# decrease selection model
# no self-attention mechanism
# full data

# Data Loading & Preprocessing

## loading climatology precipitation

In [3]:
climo_df = pd.read_csv('precip_climo.csv')

In [4]:
# Ensure time is datetime
climo_df["time"] = pd.to_datetime(climo_df["time"])

# Filter for years 1982–1984
climo_df = climo_df[
    (climo_df["time"].dt.year >= 1982) &
    (climo_df["time"].dt.year <= 1984)
]

climo_df

        latitude  longitude       time  precip_climo
87412      -10.0     -70.00 1982-01-03     17.455254
87413      -10.0     -69.75 1982-01-03     20.454031
87414      -10.0     -69.50 1982-01-03     21.781550
87415      -10.0     -69.25 1982-01-03     23.039633
87416      -10.0     -69.00 1982-01-03     24.171701
...          ...        ...        ...           ...
351324       0.0     -61.00 1984-12-30     18.504717
351325       0.0     -60.75 1984-12-30     19.413860
351326       0.0     -60.50 1984-12-30     18.435364
351327       0.0     -60.25 1984-12-30     17.345550
351328       0.0     -60.00 1984-12-30     16.988117

[263917 rows x 4 columns]

## loading amazon

In [5]:
df = pd.read_csv('amazon_1982_1984.csv')

In [6]:
df = df[(df['latitude'] <= 0) & (df['latitude'] >= -10) & (df['longitude'] <= -60) & (df['longitude'] >= -70)].reset_index(drop=True)

In [7]:
df.columns

Index(['week', 'latitude', 'longitude', 'precip_max', 'z_mean', 'z_min',
       'z_max', 'z_std', 'z_p25', 'z_p75', 't2m_mean', 't2m_min', 't2m_max',
       't2m_std', 'swvl1_mean', 'swvl1_min', 'swvl1_max', 'swvl1_std'],
      dtype='object')

In [8]:
df[(df['latitude']==-10.0) &(df['longitude']==-70.00)]

,week,latitude,longitude,precip_max,z_mean,z_min,z_max,z_std,z_p25,z_p75,t2m_mean,t2m_min,t2m_max,t2m_std,swvl1_mean,swvl1_min,swvl1_max,swvl1_std
0,1982-01-03,-10.0,-70.0,53.920998,57299.777,57094.934,57484.700,97.39884,57224.979492,57381.106445,297.094976,294.97217,303.80005,1.553519,0.477107,0.402939,0.520004,0.024311
1681,1982-01-10,-10.0,-70.0,19.614357,57295.977,57036.260,57584.523,130.51627,57198.779297,57380.193359,297.110008,294.50415,302.78564,2.047954,0.474737,0.397247,0.520004,0.025554
3362,1982-01-17,-10.0,-70.0,21.611408,57420.887,57214.117,57616.200,102.87246,57331.707031,57504.681641,298.137471,294.72876,303.98170,2.356913,0.471536,0.420258,0.520004,0.014697
5043,1982-01-24,-10.0,-70.0,59.675793,57445.840,57174.863,57700.945,122.44274,57354.431641,57535.673828,297.612650,294.83690,303.36328,2.063976,0.478310,0.413406,0.520004,0.018787
6724,1982-01-31,-10.0,-70.0,27.553007,57421.730,57216.188,57656.480,97.11432,57352.368164,57492.026367,298.166442,294.92432,304.40137,2.475648,0.472525,0.440613,0.520004,0.013322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305943,1984-12-02,-10.0,-70.0,13.217761,57297.000,57136.140,57478.266,104.86479,57194.148438,57387.768555,297.970376,294.59375,303.56860,2.412716,0.473545,0.401917,0.520004,0.013066
309304,1984-12-09,-10.0,-70.0,52.271850,57329.810,57116.586,57523.902,102.65150,57237.964844,57415.329102,297.340830,293.99707,303.19214,1.920816,0.479858,0.405304,0.520004,0.017691
310985,1984-12-16,-10.0,-70.0,16.090420,57263.920,57026.870,57518.098,118.33471,57162.831055,57341.011719,298.072969,294.54395,304.60498,2.656609,0.472368,0.409424,0.520004,0.016673
312666,1984-12-23,-10.0,-70.0,20.289717,57224.547,56979.590,57474.074,109.87511,57138.765625,57306.655273,298.016097,294.31860,304.24536,2.530852,0.453458,0.399277,0.520004,0.024784
314347,1984-12-30,-10.0,-70.0,34.264786,57283.910,56972.312,57560.370,146.04207,57176.004883,57407.229492,297.522749,294.66016,303.19850,1.883657,0.478076,0.403870,0.520004,0.017076

In [9]:
climo_df = climo_df.rename(columns={"time": "week"})

In [10]:
climo_df["week"] = pd.to_datetime(climo_df["week"])
df["week"] = pd.to_datetime(df["week"])

In [11]:
df = pd.merge(
    df,
    climo_df,
    on=["latitude", "longitude", "week"],
    how="inner"
)

In [12]:
print(df.shape)
print(df.head())

(316028, 19)
        week  latitude  longitude  precip_max     z_mean      z_min     z_max  \
0 1982-01-03     -10.0     -70.00   53.920998  57299.777  57094.934  57484.70
1 1982-01-03     -10.0     -69.75   52.655270  57299.234  57092.934  57481.20
2 1982-01-03     -10.0     -69.50   54.742490  57303.430  57097.434  57482.45
3 1982-01-03     -10.0     -69.25   53.261463  57303.168  57097.684  57481.95
4 1982-01-03     -10.0     -69.00   55.323917  57306.160  57101.684  57486.70

      z_std         z_p25         z_p75    t2m_mean    t2m_min    t2m_max  \
0  97.39884  57224.979492  57381.106445  297.094976  294.97217  303.80005
1  96.57474  57225.404297  57380.173828  297.150437  294.80664  301.67114
2  95.29932  57231.651367  57386.486328  297.289216  295.03320  302.14966
3  94.47691  57229.719727  57389.490234  297.482480  295.50195  304.60670
4  94.23981  57233.131836  57391.543945  297.389318  295.46484  303.31372

    t2m_std  swvl1_mean  swvl1_min  swvl1_max  swvl1_std  precip_climo
0  1.553519    0.477107   0.402939   0.520004   0.024311     17.455254
1  1.456852    0.470523   0.399017   0.520004   0.025168     20.454031
2  1.502772    0.471880   0.410568   0.520004   0.024140     21.781550
3  1.738924    0.478682   0.432877   0.520004   0.018482     23.039633
4  1.693860    0.475455   0.394058   0.520004   0.023280     24.171701

In [13]:
df.columns

Index(['week', 'latitude', 'longitude', 'precip_max', 'z_mean', 'z_min',
       'z_max', 'z_std', 'z_p25', 'z_p75', 't2m_mean', 't2m_min', 't2m_max',
       't2m_std', 'swvl1_mean', 'swvl1_min', 'swvl1_max', 'swvl1_std',
       'precip_climo'],
      dtype='object')

In [14]:
# ============================
# 0. Hyperparameters
# ============================

HIST_WINDOW = 12      # number of past weeks (encoder length)
FUTURE_HORIZON = 12   # number of future weeks (decoder length)

# ============================
# 1. Define column groups
# ============================

print("✅ [Step 1] Defining column groups...")

# Static features (do NOT change). These will be label-encoded later.
static_cols = ['latitude', 'longitude']

# Historical inputs (past 12 weeks) - includes month as a feature
hist_cols = [
    'month',                # categorical but treated as numeric feature
    'precip_max',
    'swvl1_mean','swvl1_min','swvl1_max','swvl1_std',
    'z_mean','z_min','z_max','z_std','z_p25','z_p75',
    't2m_mean','t2m_min','t2m_max','t2m_std',
    'precip_climo'
]

# Future known reals (next 12 weeks)
future_real_cols = [
    't2m_mean','t2m_min','t2m_max','t2m_std', 'precip_climo'
]

# Future known categoricals (next 12 weeks)
future_cat_cols = ['month']

# Combined future inputs in time dimension
future_cols = future_cat_cols + future_real_cols

target_col = 'precip_max'

# Categorical columns that will be label-encoded
cat_cols = ['month', 'latitude', 'longitude']

print("   static_cols:", static_cols)
print("   hist_cols  :", hist_cols)
print("   future_cols:", future_cols)
print("   target_col :", target_col)


# ============================
# 2. Sort & time handling
# ============================

print("\n✅ [Step 2] Sorting df and creating 'week' + 'month'...")

# Assumes you already have a DataFrame named df
# df columns include: week, latitude, longitude, precip_max, t2m_*, swvl1_*, z_*, etc.

df = df.sort_values(['latitude', 'longitude', 'week']).reset_index(drop=True)

df['week'] = pd.to_datetime(df['week'])
df['month'] = df['week'].dt.month

print("   df shape after sort:", df.shape)
print("   week range:", df['week'].min(), "→", df['week'].max())


# ============================
# 3. Label-encode categoricals
# ============================

print("\n✅ [Step 3] Label-encoding categorical columns (month, latitude, longitude)...")

label_encoders = {}
for c in cat_cols:
    le = LabelEncoder()
    df[c] = le.fit_transform(df[c])
    label_encoders[c] = le
    print(f"   Encoded {c}: {len(le.classes_)} unique values")

# NOTE:
# - 'month' is now an integer ID (0..11)
# - 'latitude' and 'longitude' are integer IDs (for static embeddings / static inputs)


# ============================
# 4. Train / test split in time
# ============================

print("\n✅ [Step 4] Holding out last 12 weeks globally...")

max_week = df['week'].max()
cutoff = max_week - pd.Timedelta(weeks=FUTURE_HORIZON)

train_df = df[df['week'] <= cutoff].copy()
test_df  = df[df['week'] > cutoff].copy()

print("   Cutoff date :", cutoff)
print("   train_df shape:", train_df.shape)
print("   test_df shape :", test_df.shape)


# ============================
# 5. Sliding window builder
# ============================

print("\n✅ [Step 5] Building sliding window function...")

def build_windows(group, k=HIST_WINDOW, tau=FUTURE_HORIZON):
    """
    group: DataFrame for a single (lat, lon) series, sorted by week.

    Returns:
        X_hist:   (n_samples, k,   len(hist_cols))
        X_future:(n_samples, tau,  len(future_cols))
        X_static:(n_samples,       len(static_cols))
        y:       (n_samples,)
    """
    group = group.reset_index(drop=True)

    X_hist, X_future, X_static, y = [], [], [], []

    # we need k past points and tau future points, so t runs:
    # t = k, ..., len(group) - tau - 1
    for t in range(k, len(group) - tau):
        # Historical window: [t-k, ..., t-1]
        hist_block = group.loc[t-k:t-1, hist_cols].values

        # Future known window: [t, ..., t+tau-1]
        fut_block  = group.loc[t:t+tau-1, future_cols].values

        # Static inputs taken at time t (or any index, since static)
        static_vec = group.loc[t, static_cols].values  # (len(static_cols),)

        # Target at the horizon end: time t+tau-1
        target_val = group.loc[t+tau-1, target_col]

        X_hist.append(hist_block)
        X_future.append(fut_block)
        X_static.append(static_vec)
        y.append(target_val)

    return (
        np.array(X_hist),
        np.array(X_future),
        np.array(X_static),
        np.array(y)
    )

print("   Window builder ready.")


# ============================
# 6. Build windows per grid point
# ============================

print("\n✅ [Step 6] Building windows for each (latitude, longitude) group...")

all_hist, all_fut, all_stat, all_y = [], [], [], []

group_count = 0
total_samples = 0

for (lat_id, lon_id), g in train_df.groupby(['latitude', 'longitude']):
    group_count += 1
    print(f"   ▶ Group {group_count}: (lat_id={lat_id}, lon_id={lon_id}), rows={len(g)}")

    Xh, Xf, Xs, yy = build_windows(g)

    if len(yy) == 0:
        print("     ⚠ Skipped (not enough history + future)")
        continue

    print(f"     Created {len(yy)} samples for this group.")

    total_samples += len(yy)
    all_hist.append(Xh)
    all_fut.append(Xf)
    all_stat.append(Xs)
    all_y.append(yy)

print("\n   Total groups processed :", group_count)
print("   Total samples created  :", total_samples)


# ============================
# 7. Stack into final tensors
# ============================

print("\n✅ [Step 7] Stacking all group windows into final numpy arrays...")

X_hist   = np.vstack(all_hist)    # (N, HIST_WINDOW, len(hist_cols))
X_future = np.vstack(all_fut)     # (N, FUTURE_HORIZON, len(future_cols))
X_static = np.vstack(all_stat)    # (N, len(static_cols))
y        = np.concatenate(all_y)  # (N,)

print("✅ [FINAL SHAPES]")
print("   X_hist  :", X_hist.shape)    # (N, 12, 17)
print("   X_future:", X_future.shape)  # (N, 12, 6)
print("   X_static:", X_static.shape)  # (N, 2)
print("   y       :", y.shape)         # (N,)


# ============================
# 8. Quick sanity check
# ============================

print("\n✅ [Step 8] Sanity check on first sample:")

print("   Past months (first sample):")
print("   ", X_hist[0, :, 0])  # month over past 12 weeks

print("   Future months (first sample):")
print("   ", X_future[0, :, 0])  # month over next 12 weeks

print("   Static (lat_id, lon_id):")
print("   ", X_static[0])

print("   Target y (precip_max at t+12):")
print("   ", y[0])

print("\n🎉 Preprocessing pipeline finished successfully.")

✅ [Step 1] Defining column groups...
   static_cols: ['latitude', 'longitude']
   hist_cols  : ['month', 'precip_max', 'swvl1_mean', 'swvl1_min', 'swvl1_max', 'swvl1_std', 'z_mean', 'z_min', 'z_max', 'z_std', 'z_p25', 'z_p75', 't2m_mean', 't2m_min', 't2m_max', 't2m_std', 'precip_climo']
   future_cols: ['month', 't2m_mean', 't2m_min', 't2m_max', 't2m_std', 'precip_climo']
   target_col : precip_max

✅ [Step 2] Sorting df and creating 'week' + 'month'...
   df shape after sort: (316028, 20)
   week range: 1982-01-03 00:00:00 → 1984-12-30 00:00:00

✅ [Step 3] Label-encoding categorical columns (month, latitude, longitude)...
   Encoded month: 12 unique values
   Encoded latitude: 41 unique values
   Encoded longitude: 41 unique values

✅ [Step 4] Holding out last 12 weeks globally...
   Cutoff date : 1984-10-07 00:00:00
   train_df shape: (292494, 20)
   test_df shape : (23534, 20)

✅ [Step 5] Building sliding window function...
   Window builder ready.

✅ [Step 6] Building windows for each (latitude, longitude) group...
   ▶ Group 1: (lat_id=0, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 2: (lat_id=0, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 3: (lat_id=0, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 4: (lat_id=0, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 5: (lat_id=0, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 6: (lat_id=0, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 7: (lat_id=0, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 8: (lat_id=0, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 9: (lat_id=0, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 10: (lat_id=0, lon_id=9), rows=174
     Created 150 samples for this group.
   ▶ Group 11: (lat_id=0, lon_id=10), rows=174
     Created 150 samples for this group.
   ▶ Group 12: (lat_id=0, lon_id=11), rows=174
     Created 150 samples for this group.
   ▶ Group 13: (lat_id=0, lon_id=12), rows=174
     Created 150 samples for this group.
   ▶ Group 14: (lat_id=0, lon_id=13), rows=174
     Created 150 samples for this group.
   ▶ Group 15: (lat_id=0, lon_id=14), rows=174
     Created 150 samples for this group.
   ▶ Group 16: (lat_id=0, lon_id=15), rows=174
     Created 150 samples for this group.
   ▶ Group 17: (lat_id=0, lon_id=16), rows=174
     Created 150 samples for this group.
   ▶ Group 18: (lat_id=0, lon_id=17), rows=174
     Created 150 samples for this group.
   ▶ Group 19: (lat_id=0, lon_id=18), rows=174
     Created 150 samples for this group.
   ▶ Group 20: (lat_id=0, lon_id=19), rows=174
     Created 150 samples for this group.
   ▶ Group 21: (lat_id=0, lon_id=20), rows=174
     Created 150 samples for this group.
   ▶ Group 22: (lat_id=0, lon_id=21), rows=174
     Created 150 samples for this group.
   ▶ Group 23: (lat_id=0, lon_id=22), rows=174
     Created 150 samples for this group.
   ▶ Group 24: (lat_id=0, lon_id=23), rows=174
     Created 150 samples for this group.
   ▶ Group 25: (lat_id=0, lon_id=24), rows=174
     Created 150 samples for this group.
   ▶ Group 26: (lat_id=0, lon_id=25), rows=174
     Created 150 samples for this group.
   ▶ Group 27: (lat_id=0, lon_id=26), rows=174
     Created 150 samples for this group.
   ▶ Group 28: (lat_id=0, lon_id=27), rows=174
     Created 150 samples for this group.
   ▶ Group 29: (lat_id=0, lon_id=28), rows=174
     Created 150 samples for this group.
   ▶ Group 30: (lat_id=0, lon_id=29), rows=174
     Created 150 samples for this group.
   ▶ Group 31: (lat_id=0, lon_id=30), rows=174
     Created 150 samples for this group.
   ▶ Group 32: (lat_id=0, lon_id=31), rows=174
     Created 150 samples for this group.
   ▶ Group 33: (lat_id=0, lon_id=32), rows=174
     Created 150 samples for this group.
   ▶ Group 34: (lat_id=0, lon_id=33), rows=174
     Created 150 samples for this group.
   ▶ Group 35: (lat_id=0, lon_id=34), rows=174
     Created 150 samples for this group.
   ▶ Group 36: (lat_id=0, lon_id=35), rows=174
     Created 150 samples for this group.
   ▶ Group 37: (lat_id=0, lon_id=36), rows=174
     Created 150 samples for this group.
   ▶ Group 38: (lat_id=0, lon_id=37), rows=174
     Created 150 samples for this group.
   ▶ Group 39: (lat_id=0, lon_id=38), rows=174
     Created 150 samples for this group.
   ▶ Group 40: (lat_id=0, lon_id=39), rows=174
     Created 150 samples for this group.
   ▶ Group 41: (lat_id=0, lon_id=40), rows=174
     Created 150 samples for this group.
   ▶ Group 42: (lat_id=1, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 43: (lat_id=1, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 44: (lat_id=1, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 45: (lat_id=1, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 46: (lat_id=1, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 47: (lat_id=1, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 48: (lat_id=1, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 49: (lat_id=1, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 50: (lat_id=1, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 51: (lat_id=1, lon_id=9), rows=174
     Created 150 samples for this group.
   ▶ Group 52: (lat_id=1, lon_id=10), rows=174
     Created 150 samples for this group.
   ▶ Group 53: (lat_id=1, lon_id=11), rows=174
     Created 150 samples for this group.
   ▶ Group 54: (lat_id=1, lon_id=12), rows=174
     Created 150 samples for this group.
   ▶ Group 55: (lat_id=1, lon_id=13), rows=174
     Created 150 samples for this group.
   ▶ Group 56: (lat_id=1, lon_id=14), rows=174
     Created 150 samples for this group.
   ▶ Group 57: (lat_id=1, lon_id=15), rows=174
     Created 150 samples for this group.
   ▶ Group 58: (lat_id=1, lon_id=16), rows=174
     Created 150 samples for this group.
   ▶ Group 59: (lat_id=1, lon_id=17), rows=174
     Created 150 samples for this group.
   ▶ Group 60: (lat_id=1, lon_id=18), rows=174
     Created 150 samples for this group.
   ▶ Group 61: (lat_id=1, lon_id=19), rows=174
     Created 150 samples for this group.
   ▶ Group 62: (lat_id=1, lon_id=20), rows=174
     Created 150 samples for this group.
   ▶ Group 63: (lat_id=1, lon_id=21), rows=174
     Created 150 samples for this group.
   ▶ Group 64: (lat_id=1, lon_id=22), rows=174
     Created 150 samples for this group.
   ▶ Group 65: (lat_id=1, lon_id=23), rows=174
     Created 150 samples for this group.
   ▶ Group 66: (lat_id=1, lon_id=24), rows=174
     Created 150 samples for this group.
   ▶ Group 67: (lat_id=1, lon_id=25), rows=174
     Created 150 samples for this group.
   ▶ Group 68: (lat_id=1, lon_id=26), rows=174
     Created 150 samples for this group.
   ▶ Group 69: (lat_id=1, lon_id=27), rows=174
     Created 150 samples for this group.
   ▶ Group 70: (lat_id=1, lon_id=28), rows=174
     Created 150 samples for this group.
   ▶ Group 71: (lat_id=1, lon_id=29), rows=174
     Created 150 samples for this group.
   ▶ Group 72: (lat_id=1, lon_id=30), rows=174
     Created 150 samples for this group.
   ▶ Group 73: (lat_id=1, lon_id=31), rows=174
     Created 150 samples for this group.
   ▶ Group 74: (lat_id=1, lon_id=32), rows=174
     Created 150 samples for this group.
   ▶ Group 75: (lat_id=1, lon_id=33), rows=174
     Created 150 samples for this group.
   ▶ Group 76: (lat_id=1, lon_id=34), rows=174
     Created 150 samples for this group.
   ▶ Group 77: (lat_id=1, lon_id=35), rows=174
     Created 150 samples for this group.
   ▶ Group 78: (lat_id=1, lon_id=36), rows=174
     Created 150 samples for this group.
   ▶ Group 79: (lat_id=1, lon_id=37), rows=174
     Created 150 samples for this group.
   ▶ Group 80: (lat_id=1, lon_id=38), rows=174
     Created 150 samples for this group.
   ▶ Group 81: (lat_id=1, lon_id=39), rows=174
     Created 150 samples for this group.
   ▶ Group 82: (lat_id=1, lon_id=40), rows=174
     Created 150 samples for this group.
   ▶ Group 83: (lat_id=2, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 84: (lat_id=2, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 85: (lat_id=2, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 86: (lat_id=2, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 87: (lat_id=2, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 88: (lat_id=2, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 89: (lat_id=2, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 90: (lat_id=2, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 91: (lat_id=2, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 92: (lat_id=2, lon_id=9), rows=174
     Created 150 samples for this group.
   ▶ Group 93: (lat_id=2, lon_id=10), rows=174
     Created 150 samples for this group.
   ▶ Group 94: (lat_id=2, lon_id=11), rows=174
     Created 150 samples for this group.
   ▶ Group 95: (lat_id=2, lon_id=12), rows=174
     Created 150 samples for this group.
   ▶ Group 96: (lat_id=2, lon_id=13), rows=174
     Created 150 samples for this group.
   ▶ Group 97: (lat_id=2, lon_id=14), rows=174
     Created 150 samples for this group.
   ▶ Group 98: (lat_id=2, lon_id=15), rows=174
     Created 150 samples for this group.
   ▶ Group 99: (lat_id=2, lon_id=16), rows=174
     Created 150 samples for this group.
   ▶ Group 100: (lat_id=2, lon_id=17), rows=174
     Created 150 samples for this group.
   ▶ Group 101: (lat_id=2, lon_id=18), rows=174
     Created 150 samples for this group.
   ▶ Group 102: (lat_id=2, lon_id=19), rows=174
     Created 150 samples for this group.
   ▶ Group 103: (lat_id=2, lon_id=20), rows=174
     Created 150 samples for this group.
   ▶ Group 104: (lat_id=2, lon_id=21), rows=174
     Created 150 samples for this group.
   ▶ Group 105: (lat_id=2, lon_id=22), rows=174
     Created 150 samples for this group.
   ▶ Group 106: (lat_id=2, lon_id=23), rows=174
     Created 150 samples for this group.
   ▶ Group 107: (lat_id=2, lon_id=24), rows=174
     Created 150 samples for this group.
   ▶ Group 108: (lat_id=2, lon_id=25), rows=174
     Created 150 samples for this group.
   ▶ Group 109: (lat_id=2, lon_id=26), rows=174
     Created 150 samples for this group.
   ▶ Group 110: (lat_id=2, lon_id=27), rows=174
     Created 150 samples for this group.
   ▶ Group 111: (lat_id=2, lon_id=28), rows=174
     Created 150 samples for this group.
   ▶ Group 112: (lat_id=2, lon_id=29), rows=174
     Created 150 samples for this group.
   ▶ Group 113: (lat_id=2, lon_id=30), rows=174
     Created 150 samples for this group.
   ▶ Group 114: (lat_id=2, lon_id=31), rows=174
     Created 150 samples for this group.
   ▶ Group 115: (lat_id=2, lon_id=32), rows=174
     Created 150 samples for this group.
   ▶ Group 116: (lat_id=2, lon_id=33), rows=174
     Created 150 samples for this group.
   ▶ Group 117: (lat_id=2, lon_id=34), rows=174
     Created 150 samples for this group.
   ▶ Group 118: (lat_id=2, lon_id=35), rows=174
     Created 150 samples for this group.
   ▶ Group 119: (lat_id=2, lon_id=36), rows=174
     Created 150 samples for this group.
   ▶ Group 120: (lat_id=2, lon_id=37), rows=174
     Created 150 samples for this group.
   ▶ Group 121: (lat_id=2, lon_id=38), rows=174
     Created 150 samples for this group.
   ▶ Group 122: (lat_id=2, lon_id=39), rows=174
     Created 150 samples for this group.
   ▶ Group 123: (lat_id=2, lon_id=40), rows=174
     Created 150 samples for this group.
   ▶ Group 124: (lat_id=3, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 125: (lat_id=3, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 126: (lat_id=3, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 127: (lat_id=3, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 128: (lat_id=3, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 129: (lat_id=3, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 130: (lat_id=3, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 131: (lat_id=3, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 132: (lat_id=3, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 133: (lat_id=3, lon_id=9), rows=174
     Created 150 samples for this group.
   ▶ Group 134: (lat_id=3, lon_id=10), rows=174
     Created 150 samples for this group.
   ▶ Group 135: (lat_id=3, lon_id=11), rows=174
     Created 150 samples for this group.
   ▶ Group 136: (lat_id=3, lon_id=12), rows=174
     Created 150 samples for this group.
   ▶ Group 137: (lat_id=3, lon_id=13), rows=174
     Created 150 samples for this group.
   ▶ Group 138: (lat_id=3, lon_id=14), rows=174
     Created 150 samples for this group.
   ▶ Group 139: (lat_id=3, lon_id=15), rows=174
     Created 150 samples for this group.
   ▶ Group 140: (lat_id=3, lon_id=16), rows=174
     Created 150 samples for this group.
   ▶ Group 141: (lat_id=3, lon_id=17), rows=174
     Created 150 samples for this group.
   ▶ Group 142: (lat_id=3, lon_id=18), rows=174
     Created 150 samples for this group.
   ▶ Group 143: (lat_id=3, lon_id=19), rows=174
     Created 150 samples for this group.
   ▶ Group 144: (lat_id=3, lon_id=20), rows=174
     Created 150 samples for this group.
   ▶ Group 145: (lat_id=3, lon_id=21), rows=174
     Created 150 samples for this group.
   ▶ Group 146: (lat_id=3, lon_id=22), rows=174
     Created 150 samples for this group.
   ▶ Group 147: (lat_id=3, lon_id=23), rows=174
     Created 150 samples for this group.
   ▶ Group 148: (lat_id=3, lon_id=24), rows=174
     Created 150 samples for this group.
   ▶ Group 149: (lat_id=3, lon_id=25), rows=174
     Created 150 samples for this group.
   ▶ Group 150: (lat_id=3, lon_id=26), rows=174
     Created 150 samples for this group.
   ▶ Group 151: (lat_id=3, lon_id=27), rows=174
     Created 150 samples for this group.
   ▶ Group 152: (lat_id=3, lon_id=28), rows=174
     Created 150 samples for this group.
   ▶ Group 153: (lat_id=3, lon_id=29), rows=174
     Created 150 samples for this group.
   ▶ Group 154: (lat_id=3, lon_id=30), rows=174
     Created 150 samples for this group.
   ▶ Group 155: (lat_id=3, lon_id=31), rows=174
     Created 150 samples for this group.
   ▶ Group 156: (lat_id=3, lon_id=32), rows=174
     Created 150 samples for this group.
   ▶ Group 157: (lat_id=3, lon_id=33), rows=174
     Created 150 samples for this group.
   ▶ Group 158: (lat_id=3, lon_id=34), rows=174
     Created 150 samples for this group.
   ▶ Group 159: (lat_id=3, lon_id=35), rows=174
     Created 150 samples for this group.
   ▶ Group 160: (lat_id=3, lon_id=36), rows=174
     Created 150 samples for this group.
   ▶ Group 161: (lat_id=3, lon_id=37), rows=174
     Created 150 samples for this group.
   ▶ Group 162: (lat_id=3, lon_id=38), rows=174
     Created 150 samples for this group.
   ▶ Group 163: (lat_id=3, lon_id=39), rows=174
     Created 150 samples for this group.
   ▶ Group 164: (lat_id=3, lon_id=40), rows=174
     Created 150 samples for this group.
   ▶ Group 165: (lat_id=4, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 166: (lat_id=4, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 167: (lat_id=4, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 168: (lat_id=4, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 169: (lat_id=4, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 170: (lat_id=4, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 171: (lat_id=4, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 172: (lat_id=4, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 173: (lat_id=4, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 174: (lat_id=4, lon_id=9), rows=174
     Created 150 samples for this group.
   ▶ Group 175: (lat_id=4, lon_id=10), rows=174
     Created 150 samples for this group.
   ▶ Group 176: (lat_id=4, lon_id=11), rows=174
     Created 150 samples for this group.
   ▶ Group 177: (lat_id=4, lon_id=12), rows=174
     Created 150 samples for this group.
   ▶ Group 178: (lat_id=4, lon_id=13), rows=174
     Created 150 samples for this group.
   ▶ Group 179: (lat_id=4, lon_id=14), rows=174
     Created 150 samples for this group.
   ▶ Group 180: (lat_id=4, lon_id=15), rows=174
     Created 150 samples for this group.
   ▶ Group 181: (lat_id=4, lon_id=16), rows=174
     Created 150 samples for this group.
   ▶ Group 182: (lat_id=4, lon_id=17), rows=174
     Created 150 samples for this group.
   ▶ Group 183: (lat_id=4, lon_id=18), rows=174
     Created 150 samples for this group.
   ▶ Group 184: (lat_id=4, lon_id=19), rows=174
     Created 150 samples for this group.
   ▶ Group 185: (lat_id=4, lon_id=20), rows=174
     Created 150 samples for this group.
   ▶ Group 186: (lat_id=4, lon_id=21), rows=174
     Created 150 samples for this group.
   ▶ Group 187: (lat_id=4, lon_id=22), rows=174
     Created 150 samples for this group.
   ▶ Group 188: (lat_id=4, lon_id=23), rows=174
     Created 150 samples for this group.
   ▶ Group 189: (lat_id=4, lon_id=24), rows=174
     Created 150 samples for this group.
   ▶ Group 190: (lat_id=4, lon_id=25), rows=174
     Created 150 samples for this group.
   ▶ Group 191: (lat_id=4, lon_id=26), rows=174
     Created 150 samples for this group.
   ▶ Group 192: (lat_id=4, lon_id=27), rows=174
     Created 150 samples for this group.
   ▶ Group 193: (lat_id=4, lon_id=28), rows=174
     Created 150 samples for this group.
   ▶ Group 194: (lat_id=4, lon_id=29), rows=174
     Created 150 samples for this group.
   ▶ Group 195: (lat_id=4, lon_id=30), rows=174
     Created 150 samples for this group.
   ▶ Group 196: (lat_id=4, lon_id=31), rows=174
     Created 150 samples for this group.
   ▶ Group 197: (lat_id=4, lon_id=32), rows=174
     Created 150 samples for this group.
   ▶ Group 198: (lat_id=4, lon_id=33), rows=174
     Created 150 samples for this group.
   ▶ Group 199: (lat_id=4, lon_id=34), rows=174
     Created 150 samples for this group.
   ▶ Group 200: (lat_id=4, lon_id=35), rows=174
     Created 150 samples for this group.
   ▶ Group 201: (lat_id=4, lon_id=36), rows=174
     Created 150 samples for this group.
   ▶ Group 202: (lat_id=4, lon_id=37), rows=174
     Created 150 samples for this group.
   ▶ Group 203: (lat_id=4, lon_id=38), rows=174
     Created 150 samples for this group.
   ▶ Group 204: (lat_id=4, lon_id=39), rows=174
     Created 150 samples for this group.
   ▶ Group 205: (lat_id=4, lon_id=40), rows=174
     Created 150 samples for this group.
   ▶ Group 206: (lat_id=5, lon_id=0), rows=174
     Created 150 samples for this group.
   ▶ Group 207: (lat_id=5, lon_id=1), rows=174
     Created 150 samples for this group.
   ▶ Group 208: (lat_id=5, lon_id=2), rows=174
     Created 150 samples for this group.
   ▶ Group 209: (lat_id=5, lon_id=3), rows=174
     Created 150 samples for this group.
   ▶ Group 210: (lat_id=5, lon_id=4), rows=174
     Created 150 samples for this group.
   ▶ Group 211: (lat_id=5, lon_id=5), rows=174
     Created 150 samples for this group.
   ▶ Group 212: (lat_id=5, lon_id=6), rows=174
     Created 150 samples for this group.
   ▶ Group 213: (lat_id=5, lon_id=7), rows=174
     Created 150 samples for this group.
   ▶ Group 214: (lat_id=5, lon_id=8), rows=174
     Created 150 samples for this group.
   ▶ Group 215: (lat_id=5, lon_id=9), rows=174

# GRN

In [15]:
@keras.utils.register_keras_serializable(package="tft")
class GRN(layers.Layer):
    """
    Simple Gated Residual Network (GRN) with optional context.

    - input a: (..., d_out)
    - if use_context=True, call as grn(a, c)
    - if use_context=False, call as grn(a)

    Output has same last dimension d_out so that residual a + x is valid.
    """

    def __init__(self, hidden_units, output_dim, dropout=0.0, use_context=False, **kwargs):
        super().__init__(**kwargs)
        self.hidden_units = hidden_units
        self.output_dim = output_dim
        self.dropout_rate = dropout
        self.use_context = use_context

        # define sub-layers directly; no custom build needed
        self.dense1 = layers.Dense(hidden_units, activation="elu")
        self.dense2 = layers.Dense(output_dim)

        self.gate_dense = layers.Dense(2 * output_dim)
        self.dropout = layers.Dropout(dropout)
        self.layer_norm = layers.LayerNormalization(epsilon=1e-6)

    def call(self, a, c=None, training=None):
        """
        a: (..., output_dim)
        c: (..., d_c) or None
        """
        if self.use_context:
            if c is None:
                raise ValueError("GRN created with use_context=True: call as grn(a, c)")
            x = tf.concat([a, c], axis=-1)
        else:
            if c is not None:
                raise ValueError("GRN created with use_context=False: call as grn(a)")
            x = a

        # main MLP
        x = self.dense1(x)
        x = self.dense2(x)
        x = self.dropout(x, training=training)

        # gating (GLU)
        gate_in = self.gate_dense(x)           # (..., 2 * d_out)
        linear, gate = tf.split(gate_in, 2, axis=-1)
        x = linear * tf.sigmoid(gate)          # (..., d_out)

        # residual + norm
        y = self.layer_norm(a + x)             # (..., d_out)
        return y

# Variable selection

In [16]:
@keras.utils.register_keras_serializable(package="tft")
class VariableSelectionNetwork(layers.Layer):
    """
    Variable Selection Network (VSN).

    Input:
        x:        (B, F)
        context:  (B, d_ctx) or None

    Output:
        selected: (B, d_model)
        weights:  (B, F)
    """

    def __init__(self,
                 num_features,
                 d_model,
                 hidden_units,
                 use_context=False,
                 dropout=0.0,
                 name=None):
        super().__init__(name=name)
        self.num_features = num_features
        self.d_model = d_model
        self.hidden_units = hidden_units
        self.use_context = use_context
        self.dropout = dropout

        # one embedding per feature: scalar -> d_model
        self.feature_embedders = [
            layers.Dense(d_model, name=f"embed_feat_{i}")
            for i in range(num_features)
        ]

        # one GRN per feature (no context), output dim = d_model
        self.feature_grns = [
            GRN(hidden_units=hidden_units,
                output_dim=d_model,
                dropout=dropout,
                use_context=False,
                name=f"grn_feat_{i}")
            for i in range(num_features)
        ]

        # GRN for computing selection logits from flattened embeddings:
        # input dim = F * d_model, output dim = F * d_model (for residual)
        self.flat_dim = num_features * d_model
        self.flatten_grn = GRN(
            hidden_units=hidden_units,
            output_dim=self.flat_dim,
            dropout=dropout,
            use_context=use_context,
            name="flatten_grn"
        )

        # final linear layer -> F logits
        self.weight_dense = layers.Dense(num_features, name="weight_dense")

    def call(self, x, context=None, training=None):
        """
        x: (B, F)
        context: (B, d_ctx) or None
        """
        B = tf.shape(x)[0]

        # 1. Embed each feature: (B, 1) -> (B, d_model)
        embedded_feats = []
        for i, emb in enumerate(self.feature_embedders):
            xi = x[:, i:i+1]     # (B, 1)
            ei = emb(xi)        # (B, d_model)
            embedded_feats.append(ei)

        embedded = tf.stack(embedded_feats, axis=1)  # (B, F, d_model)

        # 2. Per-feature GRN transform (no context)
        transformed_feats = []
        for i, grn in enumerate(self.feature_grns):
            ti = grn(embedded_feats[i], training=training)   # (B, d_model)
            transformed_feats.append(ti)

        transformed = tf.stack(transformed_feats, axis=1)   # (B, F, d_model)

        # 3. Compute feature weights
        flat_emb = tf.reshape(embedded, [B, self.flat_dim])  # (B, F*d_model)

        if self.use_context:
            if context is None:
                raise ValueError("VSN created with use_context=True but context=None.")
            flat_out = self.flatten_grn(flat_emb, context, training=training)
        else:
            if context is not None:
                raise ValueError("VSN created with use_context=False but context was provided.")
            flat_out = self.flatten_grn(flat_emb, training=training)

        logits = self.weight_dense(flat_out)          # (B, F)
        weights = tf.nn.softmax(logits, axis=-1)      # (B, F)

        # 4. Weighted sum
        w_expanded = tf.expand_dims(weights, axis=-1) # (B, F, 1)
        weighted = transformed * w_expanded           # (B, F, d_model)
        selected = tf.reduce_sum(weighted, axis=1)    # (B, d_model)

        return selected, weights

# TFT

In [17]:
@keras.utils.register_keras_serializable(package="tft")
class TFT(Model):
    """
    Temporal Fusion Transformer (simplified) with:
      - static variable selection (1 VSN)
      - shared historical VSN (applied across all lookback steps)
      - shared future VSN (applied across all lookforward steps)
      - LSTM encoder (historical) and decoder (future)
      - Dense head → 3 quantile predictions

    Inputs:
        x_hist:   (B, T_enc, F_hist)   e.g. (B, 12, 17)
        x_future: (B, T_dec, F_future) e.g. (B, 12,  6)
        x_static: (B, F_static)        e.g. (B, 2)

    Outputs dict:
        preds:            (B, num_quantiles)

        static_selected:  (B, d_model)
        static_weights:   (B, F_static)

        hist_selected:    (B, T_enc, d_model)
        hist_weights:     (B, T_enc, F_hist)

        future_selected:  (B, T_dec, d_model)
        future_weights:   (B, T_dec, F_future)

        encoder_output:   (B, T_enc, lstm_units)
        decoder_output:   (B, T_dec, lstm_units)
    """

    def __init__(
        self,
        lookback_steps,        # T_enc (e.g. 12)
        lookforward_steps,     # T_dec (e.g. 12)
        num_hist_features,     # 17
        num_future_features,   # 6
        num_static_features,   # 2
        d_model=64,
        vsn_hidden_units=64,
        lstm_units=64,
        dropout=0.1,
        num_quantiles=3,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.lookback_steps = lookback_steps
        self.lookforward_steps = lookforward_steps
        self.num_hist_features = num_hist_features
        self.num_future_features = num_future_features
        self.num_static_features = num_static_features
        self.d_model = d_model
        self.num_quantiles = num_quantiles

        # fixed quantiles for quantile loss
        self.quantiles = tf.constant([0.1, 0.5, 0.9], dtype=tf.float32)

        # ---------- Static variable selection ----------
        self.vsn_static = VariableSelectionNetwork(
            num_features=num_static_features,
            d_model=d_model,
            hidden_units=vsn_hidden_units,
            use_context=False,
            dropout=dropout,
            name="vsn_static",
        )

        # ---------- Shared historical VSN (with static context) ----------
        self.vsn_hist = VariableSelectionNetwork(
            num_features=num_hist_features,
            d_model=d_model,
            hidden_units=vsn_hidden_units,
            use_context=True,   # receives static_selected as context
            dropout=dropout,
            name="vsn_hist_shared",
        )

        # ---------- Shared future VSN (no context) ----------
        self.vsn_future = VariableSelectionNetwork(
            num_features=num_future_features,
            d_model=d_model,
            hidden_units=vsn_hidden_units,
            use_context=False,
            dropout=dropout,
            name="vsn_future_shared",
        )

        # ---------- LSTMs ----------
        self.encoder_lstm = layers.LSTM(
            lstm_units,
            return_sequences=True,
            return_state=True,
            name="encoder_lstm",
        )

        self.decoder_lstm = layers.LSTM(
            lstm_units,
            return_sequences=True,
            return_state=True,
            name="decoder_lstm",
        )

        # ---------- Output head (decoder → 3 values) ----------
        self.output_layer = layers.Dense(
            num_quantiles, name="quantile_head"
        )

    # --------------------------------------------------
    # Quantile loss (same as before)
    # --------------------------------------------------
    def quantile_loss(self, y_true, preds):
        """
        y_true: (B,) or (B, 1)
        preds:  (B, Q) where Q = num_quantiles (3)

        QL(y, y_hat, q) = q (y - y_hat)_+ + (1-q) (y_hat - y)_+
        """
        y_true = tf.reshape(y_true, (-1, 1))      # (B, 1)
        errors = y_true - preds                   # (B, Q)

        relu_pos = tf.nn.relu(errors)            # (B, Q)
        relu_neg = tf.nn.relu(-errors)           # (B, Q)

        q = tf.reshape(self.quantiles, (1, -1))  # (1, Q)

        loss_per_q = q * relu_pos + (1.0 - q) * relu_neg  # (B, Q)
        loss = tf.reduce_mean(loss_per_q)                 # scalar
        return loss

    # --------------------------------------------------
    # Forward pass
    # --------------------------------------------------
    def call(self, inputs, training=None):
        x_hist, x_future, x_static = inputs

        B = tf.shape(x_hist)[0]
        T_enc = self.lookback_steps
        T_dec = self.lookforward_steps
        F_hist = self.num_hist_features
        F_future = self.num_future_features

        # ==========================================================
        # 1. Static variable selection (no time dimension)
        # ==========================================================
        static_selected, static_weights = self.vsn_static(
            x_static, training=training
        )  # (B, d_model), (B, F_static)

        # ==========================================================
        # 2. Historical VSN (shared), applied across all time steps
        # ==========================================================
        # x_hist: (B, T_enc, F_hist)
        # repeat static context for each encoder time step
        static_ctx_time = tf.tile(
            tf.expand_dims(static_selected, axis=1),  # (B, 1, d_model)
            [1, T_enc, 1],
        )  # (B, T_enc, d_model)

        # flatten time → (B*T_enc, F_hist) and context → (B*T_enc, d_model)
        x_hist_flat = tf.reshape(x_hist, [B * T_enc, F_hist])
        ctx_flat = tf.reshape(static_ctx_time, [B * T_enc, self.d_model])

        hist_sel_flat, hist_w_flat = self.vsn_hist(
            x_hist_flat, context=ctx_flat, training=training
        )  # (B*T_enc, d_model), (B*T_enc, F_hist)

        # reshape back to sequences
        hist_selected = tf.reshape(hist_sel_flat, [B, T_enc, self.d_model])
        hist_weights  = tf.reshape(hist_w_flat,   [B, T_enc, F_hist])

        # ==========================================================
        # 3. Future VSN (shared), applied across all future steps
        # ==========================================================
        # x_future: (B, T_dec, F_future)
        x_future_flat = tf.reshape(x_future, [B * T_dec, F_future])

        future_sel_flat, future_w_flat = self.vsn_future(
            x_future_flat, training=training
        )  # (B*T_dec, d_model), (B*T_dec, F_future)

        future_selected = tf.reshape(future_sel_flat, [B, T_dec, self.d_model])
        future_weights  = tf.reshape(future_w_flat,   [B, T_dec, F_future])

        # ==========================================================
        # 4. LSTM encoder/decoder
        # ==========================================================
        enc_output, state_h, state_c = self.encoder_lstm(
            hist_selected, training=training
        )  # (B, T_enc, lstm_units), (B, lstm_units)*2

        dec_output, _, _ = self.decoder_lstm(
            future_selected,
            initial_state=[state_h, state_c],
            training=training,
        )  # (B, T_dec, lstm_units)

        # ==========================================================
        # 5. Output head: last decoder step → 3 predictions
        # ==========================================================
        last_step = dec_output[:, -1, :]      # (B, lstm_units)
        preds = self.output_layer(last_step)  # (B, num_quantiles)

        return {
            "preds": preds,
            "static_selected": static_selected,
            "static_weights": static_weights,
            "hist_selected": hist_selected,
            "hist_weights": hist_weights,
            "future_selected": future_selected,
            "future_weights": future_weights,
            "encoder_output": enc_output,
            "decoder_output": dec_output,
        }

In [18]:
lambda_smooth = 0.05  # tune this (e.g. try 0.01, 0.05, 0.1)

def spatial_smoothness_loss(preds, x_static, eps=1e-6):
    """
    preds   : (B, Q) -> TFT quantile predictions per sample
    x_static: (B, 2) -> [latitude_id, longitude_id] (label-encoded ints)

    We use the median quantile (index 1) to enforce spatial smoothness:
        L_smooth = mean_{(i,j) neighbors} (y_hat_i - y_hat_j)^2
    where neighbors differ by ±1 in encoded latitude OR ±1 in encoded longitude.
    """
    # pick median quantile
    y_hat = preds[:, 1]  # (B,)

    lat = tf.cast(x_static[:, 0:1], tf.float32)  # (B,1)
    lon = tf.cast(x_static[:, 1:2], tf.float32)  # (B,1)

    # Pairwise differences in encoded ID space
    dlat = lat - tf.transpose(lat)  # (B,B)
    dlon = lon - tf.transpose(lon)  # (B,B)

    # Adjacent in latitude: difference = ±1
    up_down = (
        tf.abs(dlat - 1.0) < eps
    ) | (
        tf.abs(dlat + 1.0) < eps
    )

    # Adjacent in longitude: difference = ±1
    left_right = (
        tf.abs(dlon - 1.0) < eps
    ) | (
        tf.abs(dlon + 1.0) < eps
    )

    neighbor_mask = tf.logical_or(up_down, left_right)

    # Remove self-pairs (i == j)
    B = tf.shape(lat)[0]
    eye = tf.eye(B, dtype=tf.bool)
    neighbor_mask = tf.logical_and(neighbor_mask, tf.logical_not(eye))

    # Pairwise prediction differences
    diff  = tf.expand_dims(y_hat, 1) - tf.expand_dims(y_hat, 0)  # (B,B)
    diff2 = tf.square(diff)

    # Keep only neighbor pairs
    diff2_neighbors = tf.boolean_mask(diff2, neighbor_mask)

    smooth_loss = tf.cond(
        tf.size(diff2_neighbors) > 0,
        lambda: tf.reduce_mean(diff2_neighbors),
        lambda: tf.constant(0.0, dtype=tf.float32),
    )
    return smooth_loss

# Training

In [19]:
print(X_hist.shape)
print(X_future.shape)
print(X_static.shape)
print(y.shape)

(252150, 12, 17)
(252150, 12, 6)
(252150, 2)
(252150,)

In [25]:
tft = TFT(
    lookback_steps=HIST_WINDOW,
    lookforward_steps=FUTURE_HORIZON,
    num_hist_features=len(hist_cols),      # 17
    num_future_features=len(future_cols),  # 6
    num_static_features=len(static_cols),  # 2 (latitude_id, longitude_id)
    d_model=64,
    vsn_hidden_units=64,
    lstm_units=64,
    dropout=0.1,
    num_quantiles=3,
)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

In [26]:
X_hist_tf   = tf.convert_to_tensor(X_hist,   dtype=tf.float32)
X_future_tf = tf.convert_to_tensor(X_future, dtype=tf.float32)
X_static_tf = tf.convert_to_tensor(X_static, dtype=tf.float32)

In [27]:
test_out = tft(
    (X_hist_tf[:4], X_future_tf[:4], X_static_tf[:4]),
    training=False
)
print(test_out["preds"].shape)  # should be (4, 3)

(4, 3)

In [28]:
# ensure float32
X_hist_tf   = tf.convert_to_tensor(X_hist,   dtype=tf.float32)
X_future_tf = tf.convert_to_tensor(X_future, dtype=tf.float32)
X_static_tf = tf.convert_to_tensor(X_static, dtype=tf.float32)
y_tf        = tf.convert_to_tensor(y,        dtype=tf.float32)

batch_size = 256
epochs = 10

dataset = tf.data.Dataset.from_tensor_slices(
    ((X_hist_tf, X_future_tf, X_static_tf), y_tf)
)
dataset = dataset.shuffle(buffer_size=10000).batch(batch_size).prefetch(tf.data.AUTOTUNE)

steps_per_epoch = int(np.ceil(X_hist.shape[0] / batch_size))
print("Steps per epoch:", steps_per_epoch)

Steps per epoch: 985

In [29]:
@tf.function
def train_step(x_hist_b, x_future_b, x_static_b, y_b):
    with tf.GradientTape() as tape:
        outputs = tft((x_hist_b, x_future_b, x_static_b), training=True)
        preds = outputs["preds"]  # (B, 3) for 3 quantiles

        base_loss   = tft.quantile_loss(y_b, preds)
        smooth_loss = spatial_smoothness_loss(preds, x_static_b)

        loss = base_loss + lambda_smooth * smooth_loss

    grads = tape.gradient(loss, tft.trainable_variables)
    optimizer.apply_gradients(zip(grads, tft.trainable_variables))
    return base_loss, smooth_loss, loss


# ============================
# Training loop
# ============================

with open("training_smooth_ver.log", "w", encoding="utf-8") as log_file:

    for epoch in range(epochs):
        msg = f"\nEpoch {epoch+1}/{epochs}"
        print(msg)
        log_file.write(msg + "\n")
        log_file.flush()

        epoch_loss = 0.0

        for step, ((x_hist_b, x_future_b, x_static_b), y_b) in enumerate(dataset):
            base_l, smooth_l, loss = train_step(
                x_hist_b, x_future_b, x_static_b, y_b
            )

            loss_val   = float(loss.numpy())
            base_val   = float(base_l.numpy())
            smooth_val = float(smooth_l.numpy())

            epoch_loss += loss_val

            if (step + 1) % 50 == 0 or (step + 1) == steps_per_epoch:
                avg_loss = epoch_loss / (step + 1)

                msg = (
                    f"Step {step+1:4d}/{steps_per_epoch} | "
                    f"batch_loss={loss_val:.4f} | "
                    f"base={base_val:.4f} | "
                    f"smooth={smooth_val:.4f} | "
                    f"avg_loss={avg_loss:.4f}"
                )

                print(" ", msg)
                log_file.write(msg + "\n")
                log_file.flush()

Epoch 1/10
  Step   50/985 | batch_loss=4.4888 | base=4.4888 | smooth=0.0005 | avg_loss=5.6394
  Step  100/985 | batch_loss=4.5508 | base=4.5508 | smooth=0.0001 | avg_loss=5.0042
  Step  150/985 | batch_loss=4.0610 | base=4.0610 | smooth=0.0002 | avg_loss=4.7040
  Step  200/985 | batch_loss=3.7871 | base=3.7740 | smooth=0.2621 | avg_loss=4.5157
  Step  250/985 | batch_loss=3.7044 | base=3.6842 | smooth=0.4033 | avg_loss=4.3789
  Step  300/985 | batch_loss=3.6748 | base=3.6503 | smooth=0.4909 | avg_loss=4.2484
  Step  350/985 | batch_loss=2.9671 | base=2.9458 | smooth=0.4263 | avg_loss=4.1165
  Step  400/985 | batch_loss=2.9099 | base=2.8912 | smooth=0.3732 | avg_loss=3.9979
  Step  450/985 | batch_loss=2.7737 | base=2.7594 | smooth=0.2846 | avg_loss=3.8956
  Step  500/985 | batch_loss=3.1649 | base=3.1520 | smooth=0.2579 | avg_loss=3.8077
  Step  550/985 | batch_loss=2.9167 | base=2.9020 | smooth=0.2934 | avg_loss=3.7210
  Step  600/985 | batch_loss=2.9075 | base=2.8958 | smooth=0.2335 | avg_loss=3.6539
  Step  650/985 | batch_loss=3.0968 | base=3.0900 | smooth=0.1350 | avg_loss=3.6081
  Step  700/985 | batch_loss=2.9970 | base=2.9933 | smooth=0.0755 | avg_loss=3.5737
  Step  750/985 | batch_loss=2.9584 | base=2.9448 | smooth=0.2712 | avg_loss=3.5491
  Step  800/985 | batch_loss=3.1527 | base=3.1455 | smooth=0.1445 | avg_loss=3.5255
  Step  850/985 | batch_loss=2.7770 | base=2.7674 | smooth=0.1921 | avg_loss=3.4973
  Step  900/985 | batch_loss=3.0539 | base=3.0446 | smooth=0.1868 | avg_loss=3.4728
  Step  950/985 | batch_loss=3.0498 | base=3.0395 | smooth=0.2049 | avg_loss=3.4525
  Step  985/985 | batch_loss=3.2271 | base=3.2175 | smooth=0.1919 | avg_loss=3.4409

Epoch 2/10
  Step   50/985 | batch_loss=2.7085 | base=2.6791 | smooth=0.5886 | avg_loss=2.8799
  Step  100/985 | batch_loss=2.7162 | base=2.6834 | smooth=0.6558 | avg_loss=2.8176
  Step  150/985 | batch_loss=2.6285 | base=2.5863 | smooth=0.8448 | avg_loss=2.8155
  Step  200/985 | batch_loss=3.0335 | base=3.0074 | smooth=0.5212 | avg_loss=2.8341
  Step  250/985 | batch_loss=2.8810 | base=2.8559 | smooth=0.5017 | avg_loss=2.8647
  Step  300/985 | batch_loss=2.8883 | base=2.8620 | smooth=0.5264 | avg_loss=2.8681
  Step  350/985 | batch_loss=2.8789 | base=2.8561 | smooth=0.4551 | avg_loss=2.8640
  Step  400/985 | batch_loss=2.7432 | base=2.7296 | smooth=0.2710 | avg_loss=2.8584
  Step  450/985 | batch_loss=2.6690 | base=2.6548 | smooth=0.2840 | avg_loss=2.8532
  Step  500/985 | batch_loss=2.6960 | base=2.6821 | smooth=0.2776 | avg_loss=2.8436
  Step  550/985 | batch_loss=2.7160 | base=2.7056 | smooth=0.2085 | avg_loss=2.8342
  Step  600/985 | batch_loss=2.9980 | base=2.9864 | smooth=0.2324 | avg_loss=2.8319
  Step  650/985 | batch_loss=2.7713 | base=2.7652 | smooth=0.1225 | avg_loss=2.8392
  Step  700/985 | batch_loss=2.9058 | base=2.8942 | smooth=0.2312 | avg_loss=2.8538
  Step  750/985 | batch_loss=3.0989 | base=3.0895 | smooth=0.1881 | avg_loss=2.8720
  Step  800/985 | batch_loss=3.3051 | base=3.2968 | smooth=0.1659 | avg_loss=2.8854
  Step  850/985 | batch_loss=3.2755 | base=3.2639 | smooth=0.2314 | avg_loss=2.8936
  Step  900/985 | batch_loss=3.1756 | base=3.1659 | smooth=0.1959 | avg_loss=2.9002
  Step  950/985 | batch_loss=3.1516 | base=3.1391 | smooth=0.2514 | avg_loss=2.9071
  Step  985/985 | batch_loss=2.7447 | base=2.7354 | smooth=0.1846 | avg_loss=2.9134

Epoch 3/10
  Step   50/985 | batch_loss=2.5169 | base=2.4914 | smooth=0.5111 | avg_loss=2.7793
  Step  100/985 | batch_loss=3.3383 | base=3.3107 | smooth=0.5503 | avg_loss=2.7367
  Step  150/985 | batch_loss=3.0076 | base=2.9702 | smooth=0.7488 | avg_loss=2.7466
  Step  200/985 | batch_loss=3.0673 | base=3.0292 | smooth=0.7604 | avg_loss=2.7768
  Step  250/985 | batch_loss=3.1814 | base=3.1511 | smooth=0.6064 | avg_loss=2.8029
  Step  300/985 | batch_loss=2.6241 | base=2.5931 | smooth=0.6206 | avg_loss=2.8176
  Step  350/985 | batch_loss=2.9483 | base=2.9292 | smooth=0.3821 | avg_loss=2.8128
  Step  400/985 | batch_loss=3.0482 | base=3.0320 | smooth=0.3245 | avg_loss=2.8108
  Step  450/985 | batch_loss=2.8613 | base=2.8462 | smooth=0.3024 | avg_loss=2.8095
  Step  500/985 | batch_loss=3.0146 | base=2.9987 | smooth=0.3180 | avg_loss=2.8065
  Step  550/985 | batch_loss=2.6199 | base=2.6062 | smooth=0.2749 | avg_loss=2.7960
  Step  600/985 | batch_loss=3.0313 | base=3.0189 | smooth=0.2482 | avg_loss=2.7965
  Step  650/985 | batch_loss=3.1251 | base=3.1153 | smooth=0.1955 | avg_loss=2.8072
  Step  700/985 | batch_loss=3.1335 | base=3.1251 | smooth=0.1693 | avg_loss=2.8211
  Step  750/985 | batch_loss=3.1319 | base=3.1238 | smooth=0.1633 | avg_loss=2.8413
  Step  800/985 | batch_loss=2.9883 | base=2.9777 | smooth=0.2121 | avg_loss=2.8566
  Step  850/985 | batch_loss=2.8969 | base=2.8883 | smooth=0.1728 | avg_loss=2.8667
  Step  900/985 | batch_loss=2.7932 | base=2.7810 | smooth=0.2440 | avg_loss=2.8731
  Step  950/985 | batch_loss=3.2917 | base=3.2831 | smooth=0.1726 | avg_loss=2.8814
  Step  985/985 | batch_loss=3.0739 | base=3.0641 | smooth=0.1956 | avg_loss=2.8884

Epoch 4/10
  Step   50/985 | batch_loss=2.7395 | base=2.7091 | smooth=0.6069 | avg_loss=2.7772
  Step  100/985 | batch_loss=2.6710 | base=2.6469 | smooth=0.4823 | avg_loss=2.7193
  Step  150/985 | batch_loss=2.9188 | base=2.8976 | smooth=0.4242 | avg_loss=2.7298
  Step  200/985 | batch_loss=2.5508 | base=2.5185 | smooth=0.6464 | avg_loss=2.7559
  Step  250/985 | batch_loss=2.8508 | base=2.8216 | smooth=0.5836 | avg_loss=2.7934
  Step  300/985 | batch_loss=2.8453 | base=2.8183 | smooth=0.5399 | avg_loss=2.8060
  Step  350/985 | batch_loss=2.7810 | base=2.7620 | smooth=0.3792 | avg_loss=2.8049
  Step  400/985 | batch_loss=2.7007 | base=2.6865 | smooth=0.2830 | avg_loss=2.8036
  Step  450/985 | batch_loss=2.7387 | base=2.7252 | smooth=0.2704 | avg_loss=2.8022
  Step  500/985 | batch_loss=2.6598 | base=2.6488 | smooth=0.2209 | avg_loss=2.7979
  Step  550/985 | batch_loss=2.8771 | base=2.8640 | smooth=0.2631 | avg_loss=2.7887
  Step  600/985 | batch_loss=2.8883 | base=2.8758 | smooth=0.2491 | avg_loss=2.7856
  Step  650/985 | batch_loss=3.0641 | base=3.0520 | smooth=0.2420 | avg_loss=2.7975
  Step  700/985 | batch_loss=2.8738 | base=2.8604 | smooth=0.2673 | avg_loss=2.8164
  Step  750/985 | batch_loss=3.0390 | base=3.0248 | smooth=0.2836 | avg_loss=2.8321
  Step  800/985 | batch_loss=3.2559 | base=3.2483 | smooth=0.1519 | avg_loss=2.8497
  Step  850/985 | batch_loss=3.0890 | base=3.0788 | smooth=0.2041 | avg_loss=2.8617
  Step  900/985 | batch_loss=3.0566 | base=3.0463 | smooth=0.2071 | avg_loss=2.8685
  Step  950/985 | batch_loss=3.5290 | base=3.5179 | smooth=0.2223 | avg_loss=2.8761
  Step  985/985 | batch_loss=2.9320 | base=2.9225 | smooth=0.1906 | avg_loss=2.8834

Epoch 5/10
  Step   50/985 | batch_loss=2.6207 | base=2.5959 | smooth=0.4946 | avg_loss=2.7617
  Step  100/985 | batch_loss=2.6621 | base=2.6361 | smooth=0.5204 | avg_loss=2.7273
  Step  150/985 | batch_loss=2.7455 | base=2.7125 | smooth=0.6608 | avg_loss=2.7322
  Step  200/985 | batch_loss=2.7509 | base=2.7246 | smooth=0.5246 | avg_loss=2.7640
  Step  250/985 | batch_loss=2.8343 | base=2.8041 | smooth=0.6050 | avg_loss=2.7956
  Step  300/985 | batch_loss=2.8007 | base=2.7739 | smooth=0.5359 | avg_loss=2.8035
  Step  350/985 | batch_loss=2.7514 | base=2.7315 | smooth=0.3964 | avg_loss=2.8014
  Step  400/985 | batch_loss=2.7156 | base=2.6956 | smooth=0.4011 | avg_loss=2.8028
  Step  450/985 | batch_loss=2.8714 | base=2.8561 | smooth=0.3071 | avg_loss=2.8020
  Step  500/985 | batch_loss=2.7223 | base=2.7055 | smooth=0.3359 | avg_loss=2.7979
  Step  550/985 | batch_loss=2.7864 | base=2.7716 | smooth=0.2961 | avg_loss=2.7898
  Step  600/985 | batch_loss=2.7272 | base=2.7164 | smooth=0.2168 | avg_loss=2.7860
  Step  650/985 | batch_loss=2.6771 | base=2.6674 | smooth=0.1937 | avg_loss=2.7956
  Step  700/985 | batch_loss=2.9837 | base=2.9722 | smooth=0.2284 | avg_loss=2.8128
  Step  750/985 | batch_loss=2.9473 | base=2.9384 | smooth=0.1776 | avg_loss=2.8304
  Step  800/985 | batch_loss=3.0499 | base=3.0369 | smooth=0.2601 | avg_loss=2.8458
  Step  850/985 | batch_loss=3.1641 | base=3.1538 | smooth=0.2062 | avg_loss=2.8584
  Step  900/985 | batch_loss=2.8951 | base=2.8834 | smooth=0.2343 | avg_loss=2.8647
  Step  950/985 | batch_loss=3.2001 | base=3.1902 | smooth=0.1990 | avg_loss=2.8729
  Step  985/985 | batch_loss=3.5835 | base=3.5710 | smooth=0.2510 | avg_loss=2.8801

Epoch 6/10
  Step   50/985 | batch_loss=2.5631 | base=2.5331 | smooth=0.6002 | avg_loss=2.7574
  Step  100/985 | batch_loss=2.8779 | base=2.8452 | smooth=0.6533 | avg_loss=2.7061
  Step  150/985 | batch_loss=2.7616 | base=2.7263 | smooth=0.7049 | avg_loss=2.7183
  Step  200/985 | batch_loss=3.0498 | base=3.0245 | smooth=0.5056 | avg_loss=2.7526
  Step  250/985 | batch_loss=3.0172 | base=2.9940 | smooth=0.4646 | avg_loss=2.7760
  Step  300/985 | batch_loss=2.5722 | base=2.5409 | smooth=0.6245 | avg_loss=2.7923
  Step  350/985 | batch_loss=2.7909 | base=2.7639 | smooth=0.5385 | avg_loss=2.7928
  Step  400/985 | batch_loss=2.8391 | base=2.8205 | smooth=0.3712 | avg_loss=2.7903
  Step  450/985 | batch_loss=2.6723 | base=2.6599 | smooth=0.2497 | avg_loss=2.7896
  Step  500/985 | batch_loss=2.7509 | base=2.7415 | smooth=0.1898 | avg_loss=2.7860
  Step  550/985 | batch_loss=2.4504 | base=2.4390 | smooth=0.2279 | avg_loss=2.7791
  Step  600/985 | batch_loss=2.7860 | base=2.7722 | smooth=0.2770 | avg_loss=2.7784
  Step  650/985 | batch_loss=2.8213 | base=2.8098 | smooth=0.2303 | avg_loss=2.7853
  Step  700/985 | batch_loss=2.9572 | base=2.9481 | smooth=0.1820 | avg_loss=2.8053
  Step  750/985 | batch_loss=2.9506 | base=2.9401 | smooth=0.2097 | avg_loss=2.8231
  Step  800/985 | batch_loss=2.9412 | base=2.9332 | smooth=0.1595 | avg_loss=2.8412
  Step  850/985 | batch_loss=3.0795 | base=3.0681 | smooth=0.2280 | avg_loss=2.8514
  Step  900/985 | batch_loss=3.1422 | base=3.1329 | smooth=0.1865 | avg_loss=2.8567
  Step  950/985 | batch_loss=3.0278 | base=3.0159 | smooth=0.2381 | avg_loss=2.8669
  Step  985/985 | batch_loss=2.9437 | base=2.9336 | smooth=0.2035 | avg_loss=2.8736

Epoch 7/10
  Step   50/985 | batch_loss=2.6720 | base=2.6321 | smooth=0.7979 | avg_loss=2.7595
  Step  100/985 | batch_loss=2.6164 | base=2.5926 | smooth=0.4770 | avg_loss=2.7041
  Step  150/985 | batch_loss=2.6161 | base=2.5839 | smooth=0.6447 | avg_loss=2.7081
  Step  200/985 | batch_loss=2.6368 | base=2.6102 | smooth=0.5331 | avg_loss=2.7525
  Step  250/985 | batch_loss=2.8433 | base=2.8061 | smooth=0.7443 | avg_loss=2.7782
  Step  300/985 | batch_loss=2.6773 | base=2.6548 | smooth=0.4494 | avg_loss=2.7869
  Step  350/985 | batch_loss=2.8026 | base=2.7769 | smooth=0.5135 | avg_loss=2.7881
  Step  400/985 | batch_loss=2.9005 | base=2.8796 | smooth=0.4181 | avg_loss=2.7864
  Step  450/985 | batch_loss=2.7028 | base=2.6828 | smooth=0.4008 | avg_loss=2.7847
  Step  500/985 | batch_loss=2.4858 | base=2.4697 | smooth=0.3221 | avg_loss=2.7785
  Step  550/985 | batch_loss=2.8957 | base=2.8854 | smooth=0.2057 | avg_loss=2.7735
  Step  600/985 | batch_loss=2.8376 | base=2.8243 | smooth=0.2669 | avg_loss=2.7735
  Step  650/985 | batch_loss=2.9572 | base=2.9448 | smooth=0.2484 | avg_loss=2.7825
  Step  700/985 | batch_loss=3.4864 | base=3.4781 | smooth=0.1670 | avg_loss=2.8005
  Step  750/985 | batch_loss=3.2915 | base=3.2791 | smooth=0.2477 | avg_loss=2.8209
  Step  800/985 | batch_loss=2.6308 | base=2.6236 | smooth=0.1443 | avg_loss=2.8366
  Step  850/985 | batch_loss=2.9619 | base=2.9512 | smooth=0.2150 | avg_loss=2.8491
  Step  900/985 | batch_loss=2.7570 | base=2.7457 | smooth=0.2271 | avg_loss=2.8546
  Step  950/985 | batch_loss=2.8440 | base=2.8323 | smooth=0.2332 | avg_loss=2.8631
  Step  985/985 | batch_loss=3.3442 | base=3.3326 | smooth=0.2311 | avg_loss=2.8699

Epoch 8/10
  Step   50/985 | batch_loss=2.6892 | base=2.6728 | smooth=0.3294 | avg_loss=2.7510
  Step  100/985 | batch_loss=2.7230 | base=2.6937 | smooth=0.5855 | avg_loss=2.7099
  Step  150/985 | batch_loss=2.7185 | base=2.6829 | smooth=0.7125 | avg_loss=2.7170
  Step  200/985 | batch_loss=3.1104 | base=3.0806 | smooth=0.5942 | avg_loss=2.7518
  Step  250/985 | batch_loss=3.0506 | base=3.0237 | smooth=0.5380 | avg_loss=2.7828
  Step  300/985 | batch_loss=2.6924 | base=2.6666 | smooth=0.5159 | avg_loss=2.7897
  Step  350/985 | batch_loss=2.9260 | base=2.9050 | smooth=0.4207 | avg_loss=2.7891
  Step  400/985 | batch_loss=2.6994 | base=2.6799 | smooth=0.3903 | avg_loss=2.7863
  Step  450/985 | batch_loss=2.5965 | base=2.5823 | smooth=0.2836 | avg_loss=2.7866
  Step  500/985 | batch_loss=2.7212 | base=2.7064 | smooth=0.2960 | avg_loss=2.7812
  Step  550/985 | batch_loss=2.4850 | base=2.4736 | smooth=0.2283 | avg_loss=2.7737
  Step  600/985 | batch_loss=2.8601 | base=2.8503 | smooth=0.1965 | avg_loss=2.7732
  Step  650/985 | batch_loss=2.9533 | base=2.9444 | smooth=0.1777 | avg_loss=2.7862
  Step  700/985 | batch_loss=3.2917 | base=3.2821 | smooth=0.1923 | avg_loss=2.8016
  Step  750/985 | batch_loss=3.0415 | base=3.0320 | smooth=0.1912 | avg_loss=2.8202
  Step  800/985 | batch_loss=3.0697 | base=3.0596 | smooth=0.2023 | avg_loss=2.8374
  Step  850/985 | batch_loss=2.8922 | base=2.8810 | smooth=0.2241 | avg_loss=2.8488
  Step  900/985 | batch_loss=2.8147 | base=2.8050 | smooth=0.1928 | avg_loss=2.8552
  Step  950/985 | batch_loss=3.2745 | base=3.2650 | smooth=0.1906 | avg_loss=2.8635
  Step  985/985 | batch_loss=2.9686 | base=2.9581 | smooth=0.2104 | avg_loss=2.8707

Epoch 9/10
  Step   50/985 | batch_loss=2.6061 | base=2.5789 | smooth=0.5436 | avg_loss=2.7523
  Step  100/985 | batch_loss=2.6073 | base=2.5781 | smooth=0.5854 | avg_loss=2.7006
  Step  150/985 | batch_loss=2.8534 | base=2.8254 | smooth=0.5607 | avg_loss=2.7081
  Step  200/985 | batch_loss=2.9492 | base=2.9186 | smooth=0.6127 | avg_loss=2.7356
  Step  250/985 | batch_loss=2.9589 | base=2.9353 | smooth=0.4733 | avg_loss=2.7693
  Step  300/985 | batch_loss=2.5892 | base=2.5635 | smooth=0.5137 | avg_loss=2.7808
  Step  350/985 | batch_loss=2.7296 | base=2.7085 | smooth=0.4224 | avg_loss=2.7813
  Step  400/985 | batch_loss=2.8158 | base=2.7964 | smooth=0.3882 | avg_loss=2.7802
  Step  450/985 | batch_loss=2.8648 | base=2.8508 | smooth=0.2813 | avg_loss=2.7791
  Step  500/985 | batch_loss=2.9115 | base=2.8968 | smooth=0.2941 | avg_loss=2.7769
  Step  550/985 | batch_loss=2.6859 | base=2.6685 | smooth=0.3462 | avg_loss=2.7682
  Step  600/985 | batch_loss=2.7853 | base=2.7729 | smooth=0.2477 | avg_loss=2.7684
  Step  650/985 | batch_loss=2.8524 | base=2.8427 | smooth=0.1948 | avg_loss=2.7779
  Step  700/985 | batch_loss=3.0568 | base=3.0452 | smooth=0.2327 | avg_loss=2.7962
  Step  750/985 | batch_loss=2.9692 | base=2.9613 | smooth=0.1583 | avg_loss=2.8157
  Step  800/985 | batch_loss=3.0196 | base=3.0125 | smooth=0.1425 | avg_loss=2.8318
  Step  850/985 | batch_loss=2.9489 | base=2.9376 | smooth=0.2263 | avg_loss=2.8445
  Step  900/985 | batch_loss=2.9393 | base=2.9254 | smooth=0.2784 | avg_loss=2.8495
  Step  950/985 | batch_loss=3.0220 | base=3.0094 | smooth=0.2522 | avg_loss=2.8572
  Step  985/985 | batch_loss=3.3732 | base=3.3618 | smooth=0.2291 | avg_loss=2.8651

Epoch 10/10
  Step   50/985 | batch_loss=2.5618 | base=2.5413 | smooth=0.4110 | avg_loss=2.7599
  Step  100/985 | batch_loss=2.9716 | base=2.9472 | smooth=0.4877 | avg_loss=2.7094
  Step  150/985 | batch_loss=2.8719 | base=2.8470 | smooth=0.4971 | avg_loss=2.7119
  Step  200/985 | batch_loss=2.8030 | base=2.7777 | smooth=0.5074 | avg_loss=2.7424
  Step  250/985 | batch_loss=2.8090 | base=2.7830 | smooth=0.5210 | avg_loss=2.7717
  Step  300/985 | batch_loss=2.6961 | base=2.6672 | smooth=0.5778 | avg_loss=2.7818
  Step  350/985 | batch_loss=2.6428 | base=2.6254 | smooth=0.3462 | avg_loss=2.7820
  Step  400/985 | batch_loss=2.5670 | base=2.5505 | smooth=0.3288 | avg_loss=2.7735
  Step  450/985 | batch_loss=2.9037 | base=2.8873 | smooth=0.3284 | avg_loss=2.7751
  Step  500/985 | batch_loss=2.8207 | base=2.8084 | smooth=0.2446 | avg_loss=2.7717
  Step  550/985 | batch_loss=2.6112 | base=2.5980 | smooth=0.2626 | avg_loss=2.7661
  Step  600/985 | batch_loss=2.9729 | base=2.9642 | smooth=0.1751 | avg_loss=2.7643
  Step  650/985 | batch_loss=3.1707 | base=3.1531 | smooth=0.3526 | avg_loss=2.7766
  Step  700/985 | batch_loss=3.2596 | base=3.2486 | smooth=0.2212 | avg_loss=2.7932
  Step  750/985 | batch_loss=2.8968 | base=2.8871 | smooth=0.1950 | avg_loss=2.8086
  Step  800/985 | batch_loss=2.9670 | base=2.9543 | smooth=0.2540 | avg_loss=2.8282
  Step  850/985 | batch_loss=3.0333 | base=3.0207 | smooth=0.2538 | avg_loss=2.8396
  Step  900/985 | batch_loss=3.1039 | base=3.0939 | smooth=0.1987 | avg_loss=2.8455
  Step  950/985 | batch_loss=3.1829 | base=3.1731 | smooth=0.1965 | avg_loss=2.8544
  Step  985/985 | batch_loss=3.0731 | base=3.0587 | smooth=0.2881 | avg_loss=2.8614

In [30]:
# tft.save("tft_model.keras")              # FULL safe save (REQUIRED)
tft.save_weights("smooth_tft_weights.weights.h5")

In [31]:
def build_test_windows(group, cutoff_week, k=HIST_WINDOW, tau=FUTURE_HORIZON):
    """
    Build windows for test, using the FULL group (not pre-cut to train_df),
    but only keep samples whose TARGET horizon lies AFTER cutoff_week
    (i.e., in the last 12 weeks).

    group: DataFrame for a single (lat, lon) series, sorted by week.

    Returns:
        X_hist_test:   (n_test, k,   len(hist_cols))
        X_future_test: (n_test, tau, len(future_cols))
        X_static_test: (n_test,      len(static_cols))
        y_test:        (n_test,)
        target_weeks:  (n_test,)  # for debugging / inspection
    """
    group = group.sort_values("week").reset_index(drop=True)

    X_hist, X_future, X_static, y, target_weeks = [], [], [], [], []

    # same range pattern as training:
    # t = k, ..., len(group) - tau - 1
    for t in range(k, len(group) - tau):
        horizon_idx = t + tau - 1
        horizon_week = group.loc[horizon_idx, "week"]

        # only keep windows whose TARGET is in the hold-out period
        if horizon_week <= cutoff_week:
            continue

        # Historical window: [t-k, ..., t-1]
        hist_block = group.loc[t-k:t-1, hist_cols].values

        # Future known window: [t, ..., t+tau-1]
        fut_block  = group.loc[t:t+tau-1, future_cols].values

        # Static inputs at time t
        static_vec = group.loc[t, static_cols].values  # (len(static_cols),)

        # Target at horizon: precip_max at t+tau-1
        target_val = group.loc[horizon_idx, target_col]

        X_hist.append(hist_block)
        X_future.append(fut_block)
        X_static.append(static_vec)
        y.append(target_val)
        target_weeks.append(horizon_week)

    return (
        np.array(X_hist),
        np.array(X_future),
        np.array(X_static),
        np.array(y),
        np.array(target_weeks),
    )

In [32]:
print("\n✅ [TEST] Building windows whose horizon is in last 12 weeks...")

X_hist_test_list   = []
X_future_test_list = []
X_static_test_list = []
y_test_list        = []
week_test_list     = []

test_group_count = 0
test_total_samples = 0

for (lat_id, lon_id), g in df.groupby(['latitude', 'longitude']):
    test_group_count += 1
    print(f"   ▶ Test group {test_group_count}: (lat_id={lat_id}, lon_id={lon_id}), rows={len(g)}")

    Xh_t, Xf_t, Xs_t, yy_t, weeks_t = build_test_windows(
        g, cutoff_week=cutoff, k=HIST_WINDOW, tau=FUTURE_HORIZON
    )

    if len(yy_t) == 0:
        print("     ⚠ Skipped (no horizons in last 12 weeks)")
        continue

    print(f"     Created {len(yy_t)} TEST samples for this group.")
    print(f"     Horizon weeks from {weeks_t.min()} to {weeks_t.max()}")

    test_total_samples += len(yy_t)
    X_hist_test_list.append(Xh_t)
    X_future_test_list.append(Xf_t)
    X_static_test_list.append(Xs_t)
    y_test_list.append(yy_t)
    week_test_list.append(weeks_t)

print("\n   Total test groups used   :", test_group_count)
print("   Total TEST samples       :", test_total_samples)

# Stack
X_hist_test   = np.vstack(X_hist_test_list)    # (N_test, 12, len(hist_cols))
X_future_test = np.vstack(X_future_test_list)  # (N_test, 12, len(future_cols))
X_static_test = np.vstack(X_static_test_list)  # (N_test, len(static_cols))
y_test        = np.concatenate(y_test_list)    # (N_test,)
weeks_test    = np.concatenate(week_test_list) # (N_test,)

print("\n✅ [TEST FINAL SHAPES]")
print("   X_hist_test  :", X_hist_test.shape)
print("   X_future_test:", X_future_test.shape)
print("   X_static_test:", X_static_test.shape)
print("   y_test       :", y_test.shape)
print("   weeks_test   :", weeks_test.shape)
print("   Horizon week range:", weeks_test.min(), "→", weeks_test.max())

✅ [TEST] Building windows whose horizon is in last 12 weeks...
   ▶ Test group 1: (lat_id=0, lon_id=0), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 2: (lat_id=0, lon_id=1), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 3: (lat_id=0, lon_id=2), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 4: (lat_id=0, lon_id=3), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 5: (lat_id=0, lon_id=4), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 6: (lat_id=0, lon_id=5), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 7: (lat_id=0, lon_id=6), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 8: (lat_id=0, lon_id=7), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 9: (lat_id=0, lon_id=8), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 10: (lat_id=0, lon_id=9), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 11: (lat_id=0, lon_id=10), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 12: (lat_id=0, lon_id=11), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 13: (lat_id=0, lon_id=12), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 14: (lat_id=0, lon_id=13), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 15: (lat_id=0, lon_id=14), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 16: (lat_id=0, lon_id=15), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 17: (lat_id=0, lon_id=16), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 18: (lat_id=0, lon_id=17), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 19: (lat_id=0, lon_id=18), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 20: (lat_id=0, lon_id=19), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 21: (lat_id=0, lon_id=20), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 22: (lat_id=0, lon_id=21), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 23: (lat_id=0, lon_id=22), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 24: (lat_id=0, lon_id=23), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 25: (lat_id=0, lon_id=24), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 26: (lat_id=0, lon_id=25), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 27: (lat_id=0, lon_id=26), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 28: (lat_id=0, lon_id=27), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 29: (lat_id=0, lon_id=28), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 30: (lat_id=0, lon_id=29), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 31: (lat_id=0, lon_id=30), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 32: (lat_id=0, lon_id=31), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 33: (lat_id=0, lon_id=32), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 34: (lat_id=0, lon_id=33), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 35: (lat_id=0, lon_id=34), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 36: (lat_id=0, lon_id=35), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 37: (lat_id=0, lon_id=36), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 38: (lat_id=0, lon_id=37), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 39: (lat_id=0, lon_id=38), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 40: (lat_id=0, lon_id=39), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 41: (lat_id=0, lon_id=40), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 42: (lat_id=1, lon_id=0), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 43: (lat_id=1, lon_id=1), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 44: (lat_id=1, lon_id=2), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 45: (lat_id=1, lon_id=3), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 46: (lat_id=1, lon_id=4), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 47: (lat_id=1, lon_id=5), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 48: (lat_id=1, lon_id=6), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 49: (lat_id=1, lon_id=7), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 50: (lat_id=1, lon_id=8), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 51: (lat_id=1, lon_id=9), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 52: (lat_id=1, lon_id=10), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 53: (lat_id=1, lon_id=11), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 54: (lat_id=1, lon_id=12), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 55: (lat_id=1, lon_id=13), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 56: (lat_id=1, lon_id=14), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 57: (lat_id=1, lon_id=15), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 58: (lat_id=1, lon_id=16), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 59: (lat_id=1, lon_id=17), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 60: (lat_id=1, lon_id=18), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 61: (lat_id=1, lon_id=19), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 62: (lat_id=1, lon_id=20), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 63: (lat_id=1, lon_id=21), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 64: (lat_id=1, lon_id=22), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 65: (lat_id=1, lon_id=23), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 66: (lat_id=1, lon_id=24), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 67: (lat_id=1, lon_id=25), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 68: (lat_id=1, lon_id=26), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 69: (lat_id=1, lon_id=27), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 70: (lat_id=1, lon_id=28), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 71: (lat_id=1, lon_id=29), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 72: (lat_id=1, lon_id=30), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 73: (lat_id=1, lon_id=31), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 74: (lat_id=1, lon_id=32), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 75: (lat_id=1, lon_id=33), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 76: (lat_id=1, lon_id=34), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 77: (lat_id=1, lon_id=35), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 78: (lat_id=1, lon_id=36), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 79: (lat_id=1, lon_id=37), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 80: (lat_id=1, lon_id=38), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 81: (lat_id=1, lon_id=39), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 82: (lat_id=1, lon_id=40), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 83: (lat_id=2, lon_id=0), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 84: (lat_id=2, lon_id=1), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 85: (lat_id=2, lon_id=2), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 86: (lat_id=2, lon_id=3), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 87: (lat_id=2, lon_id=4), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 88: (lat_id=2, lon_id=5), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 89: (lat_id=2, lon_id=6), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 90: (lat_id=2, lon_id=7), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 91: (lat_id=2, lon_id=8), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 92: (lat_id=2, lon_id=9), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 93: (lat_id=2, lon_id=10), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 94: (lat_id=2, lon_id=11), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 95: (lat_id=2, lon_id=12), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 96: (lat_id=2, lon_id=13), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 97: (lat_id=2, lon_id=14), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 98: (lat_id=2, lon_id=15), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 99: (lat_id=2, lon_id=16), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 100: (lat_id=2, lon_id=17), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 101: (lat_id=2, lon_id=18), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 102: (lat_id=2, lon_id=19), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 103: (lat_id=2, lon_id=20), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 104: (lat_id=2, lon_id=21), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 105: (lat_id=2, lon_id=22), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 106: (lat_id=2, lon_id=23), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 107: (lat_id=2, lon_id=24), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 108: (lat_id=2, lon_id=25), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 109: (lat_id=2, lon_id=26), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 110: (lat_id=2, lon_id=27), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 111: (lat_id=2, lon_id=28), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 112: (lat_id=2, lon_id=29), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 113: (lat_id=2, lon_id=30), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 114: (lat_id=2, lon_id=31), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 115: (lat_id=2, lon_id=32), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 116: (lat_id=2, lon_id=33), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 117: (lat_id=2, lon_id=34), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 118: (lat_id=2, lon_id=35), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 119: (lat_id=2, lon_id=36), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 120: (lat_id=2, lon_id=37), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 121: (lat_id=2, lon_id=38), rows=188
     Created 13 TEST samples for this group.
     Horizon weeks from 1984-10-14 00:00:00 to 1984-12-23 00:00:00
   ▶ Test group 122: (lat_id=2, lon_id=39), rows=188
     Created 13 TEST samples for this group.

In [33]:
X_hist_test_tf   = tf.convert_to_tensor(X_hist_test,   dtype=tf.float32)
X_future_test_tf = tf.convert_to_tensor(X_future_test, dtype=tf.float32)
X_static_test_tf = tf.convert_to_tensor(X_static_test, dtype=tf.float32)
y_test_tf        = tf.convert_to_tensor(y_test,        dtype=tf.float32)

In [34]:
test_outputs = tft(
    (X_hist_test_tf, X_future_test_tf, X_static_test_tf),
    training=False
)
y_test_pred = test_outputs["preds"].numpy()   # (N_test, 3)

In [35]:
pred_df = pd.DataFrame(
    y_test_pred,
    columns=["q10", "q50", "q90"]
)

# optional: add horizon week for reference
pred_df["horizon_week"] = weeks_test

pred_df.to_csv("y_test_pred_smooth.csv", index=False)

print("Saved to y_test_pred_smooth.csv")

Saved to y_test_pred_smooth.csv

In [36]:
tft_new = TFT(
    lookback_steps=12,
    lookforward_steps=12,
    num_hist_features=17,
    num_future_features=6,
    num_static_features=2,
    d_model=64,
    vsn_hidden_units=64,
    lstm_units=64,
    dropout=0.1,
    num_quantiles=3,
)

# Shape signatures: (batch, T_enc, F_hist), (batch, T_dec, F_future), (batch, F_static)
tft_new.build([
    (None, 12, 17),
    (None, 12, 6),
    (None, 2),
])

tft_new.load_weights("tft_weights.weights.h5")
print("✅ Weights loaded.")

C:\Users\Windows 11\anaconda3\Lib\site-packages\keras\src\layers\layer.py:421: UserWarning: `build()` was called on layer 'tft_2', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(

✅ Weights loaded.